name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "*"
      
jobs:
  ci:
    uses: e-scooter-2077/azure-functions-ci/.github/workflows/azure-functions-ci.yml@master
    with:
      release-prefix: Manage Devices Functions
      azure-functionapp-name: 'scooter-physical-control-manage-devices'
      project-name: 'EScooter.PhysicalControl.ManageDevices'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
